insert into tblFilms (title, yearReleased, rating, duration, genre) values ('Mad Max: Fury Road', 2017, 'PG-13', 120, 'Drama');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('The Martian', 2020, 'G', 135, 'Drama');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('The Hunger Games: Mockingjay - Part 2', 2017, 'PG', 140, 'Action');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('The Martian', 2023, 'PG', 100, 'Documentary');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('Steve Jobs', 2022, 'G', 140, 'Documentary');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('Mad Max: Fury Road', 2020, 'PG-13', 90, 'Thriller');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('Ant-Man', 2018, 'G', 110, 'Drama');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('Mad Max: Fury Road', 2016, 'PG-13', 140, 'Fantasy');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('The Good Dinosaur', 2020, 'PG-13', 135, 'Comedy');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('The Martian', 2016, 'NC-17', 110, 'Romance');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('Spotlight', 2022, 'PG', 125, 'Fantasy');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('Creed', 2017, 'PG', 110, 'Action');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('Minions', 2020, 'NC-17', 140, 'Horror');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('Mad Max: Fury Road', 2021, 'PG-13', 90, 'Romance');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('Minions', 2017, 'PG-13', 140, 'Drama');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('The Peanuts Movie', 2022, 'PG', 120, 'Romance');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('Spotlight', 2022, 'NC-17', 120, 'Documentary');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('The Revenant', 2022, 'PG-13', 90, 'Sci-fi');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('The Secret Life of Pets', 2021, 'PG', 95, 'Documentary');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('The Hateful Eight', 2020, 'PG', 120, 'Documentary');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('The Martian', 2015, 'NC-17', 95, 'Horror');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('The Big Short', 2016, 'PG-13', 90, 'Horror');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('Inside Out', 2022, 'NC-17', 95, 'Animation');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('The Hateful Eight', 2016, 'PG', 95, 'Thriller');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('Spectre', 2019, 'R', 135, 'Drama');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('Creed', 2019, 'G', 135, 'Comedy');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('Steve Jobs', 2024, 'PG', 90, 'Thriller');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('The Revenant', 2021, 'PG-13', 95, 'Sci-fi');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('Jurassic World', 2018, 'G', 120, 'Sci-fi');
insert into tblFilms (title, yearReleased, rating, duration, genre) values ('The Danish Girl', 2020, 'R', 135, 'Sci-fi');
